apiVersion: v1
kind: Pod
metadata:
  name: sydo-deployment
  labels:
    app: joo
spec:
  containers:
    - image: joo:latest
      name: joo
      ports:
        - containerPort: 80
      imagePullPolicy: Never
  restartPolicy: Never    
---
apiVersion: v1
kind: Service
metadata:
  name: joo-service
spec:
  type: LoadBalancer
  selector:
    app: joo
  ports:
  - port: 8080
    targetPort: 80
